version: "3"
services:
  sut:
    build: .
    command: sh run_tests.sh
    environment:
      CODACY_PROJECT_TOKEN: 7f1ced6f1caf4ba0a83625fafb4d9160
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:9.5
